{% set name = "great-expectations" %}
{% set version = "0.10.12" %}
{% set sha256 = "aa195b7247a2dfe8f54daf336fce6bf828e3dad5136680b48fc1b52b0b1a7fbc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-","_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  #noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - great_expectations = great_expectations.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.14.1
    - scipy >=0.19.0
    - pandas >=0.22.0
    - python-dateutil >=2.4.2
    - pytz >=2015.6
    - six >=1.12.0
    - jsonschema >=2.5.1
    - altair >=3.1.0
    - ruamel.yaml >=0.15.24
    - ipywidgets >=7.4.2
    - requests >=2.20
    - click >=7.0
    - termcolor >=1.1.0
    - tzlocal >=1.2
    - mistune >=0.8.4
    - future >=0.16
    - jinja2 >=2.10
    - marshmallow >3.0
    - autopep8 >=1.4.4
    - black ==19.10b0
    - pyparsing >=2.4,<3
  run_constrained:
    - sqlalchemy >=1.2
    - pyspark >=2.3.2

test:
  imports:
    - great_expectations

about:
  home: https://github.com/great-expectations/great_expectations
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Always know what to expect from your data.

  description: |
    Great Expectations helps teams save time and promote analytic integrity 
    by offering a unique approach to automated testing: pipeline tests. 
    Pipeline tests are applied to data (instead of code) and at batch time 
    (instead of compile or deploy time). Pipeline tests are like unit tests 
    for datasets: they help you guard against upstream data changes and monitor 
    data quality.

    Software developers have long known that automated testing is
    essential for managing complex codebases. Great Expectations brings
    the same discipline, confidence, and acceleration to data science
    and engineering teams.
  doc_url: http://readthedocs.org/projects/great-expectations/
  dev_url: https://github.com/great-expectations/great_expectations

extra:
  recipe-maintainers:
    - sodre
    - jcampbell
    - xhochy
