{% set version = "0.15.29" %}

package:
  name: great-expectations
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/great-expectations/great_expectations-{{ version }}.tar.gz
  sha256: eb2420ec2e4ac84d46b46aa7fc04110656a97d41ab5429b2d12ef52b7aee6c46

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - great_expectations = great_expectations.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - marshmallow <4.0.0,>=3.7.1
    - makefun <2,>=1.7.0
    - notebook >=6.4.10
    - dataclasses
    - ipython >=7.16.3
    - colorama >=0.4.3
    - cryptography >=3.2
    - nbformat >=5.0
    - packaging
    - typing-extensions >=3.10.0.0
    - urllib3 <1.27,>=1.25.4
    - python >=3.6
    - altair <5,>=4.0.0
    - click >=7.1.2
    - importlib-metadata >=1.7.0
    - ipywidgets >=7.5.1
    - jinja2 >=2.10
    - jsonpatch >=1.22
    - jsonschema <=4.7.2,>=2.5.1
    - mistune >=0.8.4
    - numpy >=1.18.5
    - pandas >=1.1.0
    - pyparsing >=2.4
    - python-dateutil >=2.8.1
    - pytz >=2021.3
    - requests >=2.20
    - ruamel.yaml <0.17.18,>=0.16
    - scipy >=0.19.0
    - termcolor >=1.1.0
    - tqdm >=4.59.0
    - tzlocal >=1.2
    - typing_extensions >=3.10.0.0
    # - sqlalchemy-bigquery >=1.3.0
    # - sqlalchemy >=1.3.18
    # - snowflake-sqlalchemy >=1.2
    # - ruamel_yaml <0.17.18,>=0.16
    # - pyspark >=2.3.2
    # - psycopg2 >=2.8
    # - google-cloud-storage >=1.28.0
    # - google-cloud-secret-manager >=1.0.0
    # - boto3 >=1.14
    # - azure-keyvault-secrets >=4.0.0
    # - azure-identity >=1.0.0
    # - airflow >=1.9.0
    # - Click >=7.1.2
  run_constrained:
    - sqlalchemy >=1.3.16
    - pyspark >=2.3.2

test:
  imports:
    - great_expectations
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/great-expectations/great_expectations
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Always know what to expect from your data.

  description: |
    Great Expectations helps teams save time and promote analytic integrity
    by offering a unique approach to automated testing: pipeline tests.
    Pipeline tests are applied to data (instead of code) and at batch time
    (instead of compile or deploy time). Pipeline tests are like unit tests
    for datasets: they help you guard against upstream data changes and monitor
    data quality.

    Software developers have long known that automated testing is
    essential for managing complex codebases. Great Expectations brings
    the same discipline, confidence, and acceleration to data science
    and engineering teams.
  doc_url: https://docs.greatexpectations.io
  dev_url: https://github.com/great-expectations/great_expectations

extra:
  recipe-maintainers:
    - sodre
    - jcampbell
    - xhochy
    - alexsherstinsky
    - anthonyburdi
    - talagluck
    - Shinnnyshinshin
    - janjagusch
    - cdkini
